### ISSUE TITLE
update link in documentation

### ISSUE THREAD

**Issue by jwaldmann** [sinelaw/wl-pprint#2]
The link at the top of https://hackage.haskell.org/package/wl-pprint-1.2/docs/Text-PrettyPrint-Leijen.html
is dead. Wadler's paper now seems to be at http://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf

**Comment by sinelaw** [comment]
Thanks, updated in the source code (will still need to upload new version sometime)
