### ISSUE TITLE
Upload new version on Hackage

### ISSUE THREAD

**Issue by anton-k** [sinelaw/wl-pprint#6]
Hello! 

I develop a lib csound-expression, and I depend on wl-pprint.
I'd like to update my lib so that it builds with ghc 8.4. 
The wl-pprint in this repo builds fine with it, but the version on Hackage is very old (2015)
and fails to build due to dependency on base restriction.

Is it possible to upload this version on Hackage too?
i'd like to be able to install my lib with plain cabal.

**Comment by sinelaw** [comment]
Uploaded version 1.2.1, thanks!

**Comment by anton-k** [comment]
Thanks for quick update, Noam!
